# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rest.ui'
#
# Created: Mon Mar 16 11:41:52 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pathedit = QtGui.QLineEdit(self.frame)
        self.pathedit.setObjectName("pathedit")
        self.gridLayout.addWidget(self.pathedit, 0, 2, 1, 1)
        self.hostlabel = QtGui.QLabel(self.frame)
        self.hostlabel.setObjectName("hostlabel")
        self.gridLayout.addWidget(self.hostlabel, 0, 0, 1, 1)
        self.methodlebel = QtGui.QLabel(self.frame)
        self.methodlebel.setObjectName("methodlebel")
        self.gridLayout.addWidget(self.methodlebel, 0, 3, 1, 1)
        self.methodcombobox = QtGui.QComboBox(self.frame)
        self.methodcombobox.setObjectName("methodcombobox")
        self.methodcombobox.addItem("")
        self.methodcombobox.addItem("")
        self.methodcombobox.addItem("")
        self.methodcombobox.addItem("")
        self.methodcombobox.addItem("")
        self.methodcombobox.addItem("")
        self.gridLayout.addWidget(self.methodcombobox, 0, 4, 1, 1)
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabwidget = QtGui.QTabWidget(self.frame)
        self.tabwidget.setObjectName("tabwidget")
        self.request = QtGui.QWidget()
        self.request.setObjectName("request")
        self.gridLayout_4 = QtGui.QGridLayout(self.request)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.posttext = QtGui.QTextEdit(self.request)
        self.posttext.setObjectName("posttext")
        self.gridLayout_3.addWidget(self.posttext, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.request)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.reqheaders = QtGui.QTextEdit(self.request)
        self.reqheaders.setObjectName("reqheaders")
        self.gridLayout_3.addWidget(self.reqheaders, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.request)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.request)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.request)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.getparams = QtGui.QTextEdit(self.request)
        self.getparams.setObjectName("getparams")
        self.gridLayout_3.addWidget(self.getparams, 1, 2, 1, 1)
        self.postfile = QtGui.QLineEdit(self.request)
        self.postfile.setObjectName("postfile")
        self.gridLayout_3.addWidget(self.postfile, 3, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabwidget.addTab(self.request, "")
        self.cookies = QtGui.QWidget()
        self.cookies.setObjectName("cookies")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.cookies)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cookiestb = QtGui.QTextBrowser(self.cookies)
        self.cookiestb.setObjectName("cookiestb")
        self.verticalLayout_3.addWidget(self.cookiestb)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabwidget.addTab(self.cookies, "")
        self.response = QtGui.QWidget()
        self.response.setObjectName("response")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.response)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.responsetb = QtGui.QTextBrowser(self.response)
        self.responsetb.setObjectName("responsetb")
        self.verticalLayout_5.addWidget(self.responsetb)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabwidget.addTab(self.response, "")
        self.headers = QtGui.QWidget()
        self.headers.setObjectName("headers")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.headers)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.responseheaderstb = QtGui.QTextBrowser(self.headers)
        self.responseheaderstb.setObjectName("responseheaderstb")
        self.verticalLayout_7.addWidget(self.responseheaderstb)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.tabwidget.addTab(self.headers, "")
        self.gridLayout_2.addWidget(self.tabwidget, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        self.tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "REST Client", None, QtGui.QApplication.UnicodeUTF8))
        self.pathedit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "http(s)://ip:port/path", None, QtGui.QApplication.UnicodeUTF8))
        self.hostlabel.setText(QtGui.QApplication.translate("MainWindow", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.methodlebel.setText(QtGui.QApplication.translate("MainWindow", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.methodcombobox.setItemText(0, QtGui.QApplication.translate("MainWindow", "GET", None, QtGui.QApplication.UnicodeUTF8))
        self.methodcombobox.setItemText(1, QtGui.QApplication.translate("MainWindow", "POST", None, QtGui.QApplication.UnicodeUTF8))
        self.methodcombobox.setItemText(2, QtGui.QApplication.translate("MainWindow", "PUT", None, QtGui.QApplication.UnicodeUTF8))
        self.methodcombobox.setItemText(3, QtGui.QApplication.translate("MainWindow", "DELETE", None, QtGui.QApplication.UnicodeUTF8))
        self.methodcombobox.setItemText(4, QtGui.QApplication.translate("MainWindow", "HEAD", None, QtGui.QApplication.UnicodeUTF8))
        self.methodcombobox.setItemText(5, QtGui.QApplication.translate("MainWindow", "OPTIONS", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.posttext.setStatusTip(QtGui.QApplication.translate("MainWindow", "text to be sent in the request body, name=value pairs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "POST text payload:", None, QtGui.QApplication.UnicodeUTF8))
        self.reqheaders.setStatusTip(QtGui.QApplication.translate("MainWindow", "header:value", None, QtGui.QApplication.UnicodeUTF8))
        self.reqheaders.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head>http://localhost:8000/<meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Accept:*/*</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Cache-Control:no-cache</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "POST file upload:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "GET params:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Headers:", None, QtGui.QApplication.UnicodeUTF8))
        self.getparams.setStatusTip(QtGui.QApplication.translate("MainWindow", "name=value", None, QtGui.QApplication.UnicodeUTF8))
        self.postfile.setStatusTip(QtGui.QApplication.translate("MainWindow", "Ex: /etc/password", None, QtGui.QApplication.UnicodeUTF8))
        self.postfile.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Name,Path to file", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.request), QtGui.QApplication.translate("MainWindow", "Request", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.cookies), QtGui.QApplication.translate("MainWindow", "Cookies", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.response), QtGui.QApplication.translate("MainWindow", "Response", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.headers), QtGui.QApplication.translate("MainWindow", "Response Headers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

